Simple_CRUD/users_flask/project/users/models.py
from project import db

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.Text)

    def __init__(self, user_name):
        self.user_name = user_name

Simple_CRUD/users_flask/project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class UserForm(FlaskForm):
    user_name = StringField('user_name', validators=[DataRequired()])

Simple_CRUD/users_flask/app.py
from project import app

if __name__ == '__main__':
    app.run(debug=True, port=3000)

Simple_CRUD/users_flask/project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus

app = Flask(__name__)
modus = Modus(app)

app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/01_users'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = 'supa secret'
db = SQLAlchemy(app)

#import a blueprint that we will create
from project.users.views import users_blueprint

#register our blueprint with the application
app.register_blueprint(users_blueprint, url_prefix='/users')

@app.route('/')
def root():
    return "Users Blueprint"

Simple_CRUD/users_flask/project/users/views.py
from flask import redirect, render_template, request, url_for, Blueprint
from project.users.models import User
from project.users.forms import UserForm
from project import db

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

@users_blueprint.route('/', methods=["GET", "POST"])
def index():
    if request.method == "POST":
        form = UserForm()
        if form.validate_on_submit():
            new_user = User(request.form["user_name"])
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('users.index'))
        return render_template('users/new.html', form=form)
    return render_template('users/index.html', users=User.query.all())

@users_blueprint.route('/new')
def new():
    form = UserForm()
    return render_template('users/new.html', form=form)

@users_blueprint.route('/<int:id>/edit')
def edit(id):
    form = UserForm()
    return render_template('users/edit.html', form=form, user=User.query.get(id))

@users_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
def show(id):
    found_user = User.query.get(id)
    if found_user:
        if request.method == b"PATCH":
            form = UserForm(request.form)
            if form.validate():
                found_user.user_name = request.form["user_name"]
                db.session.add(found_user)
                db.session.commit()
                return redirect(url_for('users.index'))
            return render_template('users/edit.html', form=form, user=found_user)
        if request.method == b"DELETE":
            db.session.delete(found_user)
            db.session.commit()
            return redirect(url_for('users.index'))
        return render_template('users/show.html', user=found_user)
    return redirect(url_for('users.index'))

Simple_CRUD/users_flask/project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Users CRUD</title>
</head>
<body>
  {% block content %}
  {% endblock %}
</body>
</html>

Simple_CRUD/users_flask/project/users/templates/users/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.user_name(placeholder="Username", value=user.user_name) }}
    <span>
      {% if form.user_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  <button type="submit">Edit User</button>
</form>

{% endblock %}

Simple_CRUD/users_flask/project/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}

{% for user in users %}
  <p>{{ user.user_name }}</p>
  <form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=DELETE">
    <button type="submit">Delete this user!</button>
  </form>
{% endfor %}

{% endblock %}

Simple_CRUD/users_flask/project/users/templates/users/new.html
{% extends 'base.html' %}

{% block content %}

  <form method="POST" action="{{url_for('users.index')}}">
    {{ form.csrf_token }}
    <p>
      {{ form.user_name(placeholder="Username") }}
      <span>
        {% if form.user_name.errors %}
          {% for error in form.user_name.erros %}
            {{ error }}
          {% endfor %}
        {% endif %}
      </span>
    </p>
    <button type="submit">Add User</button>
  </form>

{% endblock %}

Simple_CRUD/users_flask/project/users/templates/users/show.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to the show page!</h1>
  {{ user.user_name }}
  <p>Delete me?</p>

  <form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=DELETE">
    <input type="submit" value="X">
  </form>
{% endblock %}